-- MySQL Script generated by MySQL Workbench
-- Fri Nov 18 21:34:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bocaditos_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bocaditos_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bocaditos_bd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bocaditos_bd` ;

-- -----------------------------------------------------
-- Table `bocaditos_bd`.`materiaprima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bocaditos_bd`.`materiaprima` (
  `matId` INT NOT NULL,
  `matNombre` VARCHAR(50) NOT NULL,
  `matCantidad` INT NOT NULL,
  `matEstado` VARCHAR(45) NOT NULL,
  `matPrecioUnidad` INT NOT NULL,
  PRIMARY KEY (`matId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bocaditos_bd`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bocaditos_bd`.`producto` (
  `proId` INT NOT NULL,
  `proNombre` VARCHAR(50) NOT NULL,
  `proCantidad` INT NOT NULL,
  `proEstado` VARCHAR(45) NOT NULL,
  `proPrecio` INT NOT NULL,
  PRIMARY KEY (`proId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bocaditos_bd`.`detallesmateriaprima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bocaditos_bd`.`detallesmateriaprima` (
  `proId_fk` INT NOT NULL,
  `matId_fk` INT NOT NULL,
  `detmCantidad` INT NULL,
  INDEX `proId_fk_idx` (`proId_fk` ASC) VISIBLE,
  INDEX `matId_fk_idx` (`matId_fk` ASC) VISIBLE,
  CONSTRAINT `matId_fk`
    FOREIGN KEY (`matId_fk`)
    REFERENCES `bocaditos_bd`.`materiaprima` (`matId`),
  CONSTRAINT `proId_fk`
    FOREIGN KEY (`proId_fk`)
    REFERENCES `bocaditos_bd`.`producto` (`proId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bocaditos_bd`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bocaditos_bd`.`roles` (
  `rolId` INT NOT NULL AUTO_INCREMENT,
  `rolDescripcion` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`rolId`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bocaditos_bd`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bocaditos_bd`.`usuario` (
  `usuId` INT NOT NULL AUTO_INCREMENT,
  `usuCorreo` VARCHAR(50) NOT NULL,
  `usuContraseña` VARCHAR(16) NOT NULL,
  `usuApellido` VARCHAR(45) NOT NULL,
  `usuNombre` VARCHAR(45) NOT NULL,
  `usuDocumento` INT NOT NULL,
  `usuTelefono` BIGINT NOT NULL,
  `usuDireccion` VARCHAR(70) NOT NULL,
  `usuEstado` VARCHAR(45) NOT NULL,
  `rolId_fk` INT NOT NULL,
  PRIMARY KEY (`usuId`),
  UNIQUE INDEX `usuCorreo_UNIQUE` (`usuCorreo` ASC) VISIBLE,
  INDEX `rolId_idx` (`rolId_fk` ASC) INVISIBLE,
  CONSTRAINT `rolId_fk`
    FOREIGN KEY (`rolId_fk`)
    REFERENCES `bocaditos_bd`.`roles` (`rolId`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bocaditos_bd`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bocaditos_bd`.`orden` (
  `ordId` INT NOT NULL AUTO_INCREMENT,
  `ordFechaEntrega` DATE NOT NULL,
  `ordFechaPedido` DATE NOT NULL,
  `ordEstado` VARCHAR(45) NOT NULL,
  `ordcliId` INT NOT NULL,
  `ordIdRepostero` INT NULL,
  `ordIdDomiciliario` INT NULL,
  PRIMARY KEY (`ordId`),
  INDEX `fk_orden_usuario1_idx` (`ordcliId` ASC) VISIBLE,
  CONSTRAINT `fk_orden_usuario1`
    FOREIGN KEY (`ordcliId`)
    REFERENCES `bocaditos_bd`.`usuario` (`usuId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bocaditos_bd`.`detallesorden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bocaditos_bd`.`detallesorden` (
  `detoId` INT NOT NULL AUTO_INCREMENT,
  `ordId_fk` INT NOT NULL,
  `prodId_fk` INT NOT NULL,
  `detoCantidad` INT NOT NULL,
  `detoDetalles` VARCHAR(50) NULL DEFAULT NULL,
  `detoPrecio` INT NOT NULL,
  `detoDescuento` INT NULL,
  INDEX `proId_fk_idx` (`prodId_fk` ASC) VISIBLE,
  INDEX `ordId_fk_idx` (`ordId_fk` ASC) VISIBLE,
  PRIMARY KEY (`detoId`),
  CONSTRAINT `ordId_fk`
    FOREIGN KEY (`ordId_fk`)
    REFERENCES `bocaditos_bd`.`orden` (`ordId`),
  CONSTRAINT `prodId_fk`
    FOREIGN KEY (`prodId_fk`)
    REFERENCES `bocaditos_bd`.`producto` (`proId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bocaditos_bd`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bocaditos_bd`.`proveedor` (
  `prvId` INT NOT NULL AUTO_INCREMENT,
  `prvNit` INT NOT NULL,
  `prvNombre` VARCHAR(50) NOT NULL,
  `prvDireccion` VARCHAR(100) NOT NULL,
  `prvTelefono` BIGINT NULL DEFAULT NULL,
  `prvCorreo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`prvId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bocaditos_bd`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bocaditos_bd`.`pedido` (
  `pedId` INT NOT NULL AUTO_INCREMENT,
  `pedFechaPedido` DATE NOT NULL,
  `pedFechaEntrega` DATE NULL,
  `pedEstado` VARCHAR(45) NOT NULL,
  `prvId_fk` INT NOT NULL,
  PRIMARY KEY (`pedId`),
  INDEX `fk_pedido_proveedor1_idx` (`prvId_fk` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_proveedor1`
    FOREIGN KEY (`prvId_fk`)
    REFERENCES `bocaditos_bd`.`proveedor` (`prvId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bocaditos_bd`.`detallespedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bocaditos_bd`.`detallespedido` (
  `detpId` INT NOT NULL AUTO_INCREMENT,
  `pedId_fk` INT NOT NULL,
  `matId_fk` INT NOT NULL,
  `detpPrecioUnidad` INT NULL,
  `detpCantidad` INT NULL,
  INDEX `fk_detallespedido_pedido1_idx` (`pedId_fk` ASC) VISIBLE,
  INDEX `fk_detallespedido_materiaprima1_idx` (`matId_fk` ASC) VISIBLE,
  PRIMARY KEY (`detpId`),
  CONSTRAINT `fk_detallespedido_pedido1`
    FOREIGN KEY (`pedId_fk`)
    REFERENCES `bocaditos_bd`.`pedido` (`pedId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallespedido_materiaprima1`
    FOREIGN KEY (`matId_fk`)
    REFERENCES `bocaditos_bd`.`materiaprima` (`matId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
